### ISSUE TITLE
pat-inject does not work with Plone 5.0

### ISSUE THREAD

**Issue by pbauer** [plone/plone.patternslib#2]
pat-inject only works in Plone 5.0.1 (hopefully coming soon). In 5.0 using pat-inject results in a js-error:
```TypeError: t.safeClone is not a function```

**Comment by jcbrand** [comment]
I've released an initial version of plone.patternslib (0.1) and the version of pat-inject in this release works, at least in the usecases @agitator and I have applied it to.

I wasn't able to replicate the TypeError you mention.
